ManageInterface/ManageInterface/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve


urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),
    path('', include('OSG.urls')),
]

ManageInterface/OSG/urls.py
from django.urls import path
from OSG.views import index, admin, account

app_name = 'OSG'

urlpatterns = [
    path('', index.home_view, name='home'),  # 將首頁路徑映射到 home view

    # 管理員的管理
    path('admin/list/', admin.admin_list_view, name='admin_list'),
    path('admin/add/', admin.admin_add_view, name='admin_add'),
    path('admin/<int:nid>/edit/', admin.admin_edit_view, name='admin_edit'),
    path('admin/<int:nid>/delete/', admin.admin_del_view, name='admin_del'),

    # 會員的管理


    # 登入
    path('login/', account.login_view, name='login'),
    # 登出
    path('logout/', account.logout_view, name='logout'),
    # 登出
    path('image/captcha/', account.captcha_view, name='captcha'),
]

ManageInterface/Booking/models.py
from django.db import models

# Create your models here.

ManageInterface/OSG/models.py
from django.db import models


class Admin(models.Model):
    """管理員表"""
    username = models.CharField(verbose_name='帳號', max_length=32)
    password = models.CharField(verbose_name='密碼', max_length=64)
    # create_time = models.DateTimeField(verbose_name='入職時間', auto_now_add=True)


class UserInfo(models.Model):
    """員工表"""
    name = models.CharField(verbose_name='姓名', max_length=32)
    password = models.CharField(verbose_name='密碼', max_length=64)
    age = models.IntegerField(verbose_name='年齡')
    salary = models.DecimalField(verbose_name='薪資', max_digits=10, decimal_places=2, default=0)

# TODO:  會員表

ManageInterface/Booking/views.py
from django.shortcuts import render

# Create your views here.

ManageInterface/OSG/views/account.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django import forms
from django.urls import reverse

from OSG import models
from OSG.utils.bootstrapStyle import BootstrapForm
from OSG.utils.captcha import check_captcha
from OSG.utils.encrypt import md5
from io import BytesIO


class LoginForm(BootstrapForm):
    username = forms.CharField(label='帳號',
                               widget=forms.TextInput(attrs={'type': 'text', 'placeholder': '帳號'}),
                               required=True)
    password = forms.CharField(label='密碼',
                               widget=forms.PasswordInput(attrs={'type': 'password', 'placeholder': '密碼'}),
                               required=True)
    captcha = forms.CharField(label='驗證碼',
                              widget=forms.TextInput(attrs={'type': 'text', 'placeholder': '請輸入驗證碼', 'id': 'captcha'}),
                              required=True)

    def clean_password(self):
        return md5(self.cleaned_data.get('password'))


def login_view(request):
    """登入"""
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 驗證成功，獲取使用者輸入的資料

        # 驗證碼校驗
        user_input_captcha = form.cleaned_data.pop('captcha')
        system_captcha = request.session.get('captcha', '')
        if user_input_captcha.upper() != system_captcha.upper():
            form.add_error('captcha', '驗證碼錯誤')
            return render(request, 'login.html', {'form': form})

        # 去資料庫驗證是否正確 admin_obj = models.Admin.objects.filter(username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password')).first()
        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            form.add_error('password', '帳號或密碼錯誤')
            return render(request, 'login.html', {'form': form})

        # 帳號密碼正確
        # 網站生成隨機字串；寫到客戶端瀏覽器cookie中，再寫入到session中；
        request.session['info'] = {'id': admin_obj.id, 'username': admin_obj.username}
        request.session.set_expiry(60*60*24*7)  # session保持7天
        return redirect(reverse('OSG:admin_list'))

    return render(request, 'login.html', {'form': form})


def captcha_view(request):
    """生成圖片驗證碼"""
    # 呼叫pillow函數，生成圖片
    img, code_string = check_captcha()
    # 寫到session中，以便後續取得並校驗
    request.session['captcha'] = code_string
    # 給session設定100秒超時
    request.session.set_expiry(100)
    print(code_string)
    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue(), content_type='image/png')


def logout_view(request):
    """登出"""
    request.session.flush()
    return redirect(reverse('OSG:login'))

ManageInterface/OSG/views/admin.py
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse

from OSG import models
from OSG.utils.paginator import Paginator
from OSG.utils.encrypt import md5
from django import forms
from OSG.utils.bootstrapStyle import BootstrapModelForm


def admin_list_view(request):
    """管理員列表"""

    # 搜尋
    data_dict = {}
    value = request.GET.get('q', '')
    if value is not None:
        data_dict['username__contains'] = value

    queryset = models.Admin.objects.filter(**data_dict)  # .order_by('-id')遞減排序

    # 分頁
    page_obj = Paginator(request, queryset)

    context = {
        'search_fields': value,
        'queryset': page_obj.page_queryset,  # 分完頁的資料
        'page_string': page_obj.html()  # 頁碼
    }
    return render(request, 'admin_list.html', context)


class AdminModelForm(BootstrapModelForm):
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(),  # 參數放render_value=True，可使送出後欄位內容不消失
        label='確認密碼'
    )

    class Meta:
        model = models.Admin
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput()
        }

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)

    def clean_confirm_password(self):
        conf_password = md5(self.cleaned_data.get('confirm_password'))
        if self.cleaned_data.get('password') != conf_password:
            raise ValidationError('密碼不一致')
        return conf_password


def admin_add_view(request):
    """新增管理員"""
    title = '新增管理員'
    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'data_add.html', {'form': form, 'title': title})

    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(reverse('OSG:admin_list'))

    return render(request, 'data_add.html', {'form': form, 'title': title})


def admin_edit_view(request, nid):
    """編輯管理員"""
    # 物件 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return render(request, 'error.html', {'msg': '資料不存在'})
    title = '編輯管理員'
    if request.method == 'GET':
        form = AdminModelForm(instance=row_object) # 使用與新增一樣的ModelForm
        return render(request, 'data_add.html', {'form': form, 'title': title})
    form = AdminModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect(reverse('OSG:admin_list'))
    return render(request, 'data_add.html', {'form': form, 'title': title})


def admin_del_view(request, nid):
    """刪除管理員"""
    models.Admin.objects.filter(id=nid).delete()
    return redirect(reverse('OSG:admin_list'))

ManageInterface/OSG/views/index.py
from django.shortcuts import render


def home_view(request):
    # 渲染模板並返回響應
    return render(request, 'index.html')

ManageInterface/OSG/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="d-flex align-items-center mb-2">
            <a href="{% url 'OSG:admin_add' %}" class="btn btn-success  me-auto">
                <i class="me-2 fa-solid fa-circle-plus"></i>
                新增管理員
            </a>
            <form class="d-flex flex-row" method="get">
                <input class="form-control me-2" name="q" value="{{ search_fields }}" type="search" placeholder="Search for..." aria-label="search">
                <button class="btn btn-outline-secondary text-nowrap" type="submit" aria-label="search"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
        <div class="card mb-2">
            <div class="card-header">
                <i class="me-2 fa-solid fa-list"></i>
                管理員列表
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">帳號</th>
                        <th scope="col">密碼</th>
                        <th scope="col">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for rec in queryset %}
                        <tr>
                            <th scope="row">{{ rec.id }}</th>
                            <td>{{ rec.username }}</td>
                            <td>******</td>
                            <td>
                                <a href="{% url 'OSG:admin_edit' nid=rec.id %}" class="btn btn-outline-primary btn-sm" role="button">編輯</a>
                                <a href="{% url 'OSG:admin_del' nid=rec.id %}" class="btn btn-outline-danger btn-sm" role="button">刪除</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div>
            <nav aria-label="Page navigation">
              <ul class="pagination">
                  {{ page_string }}
              </ul>
            </nav>
        </div>
    </div>

{% endblock %}

ManageInterface/OSG/templates/data_add.html
{% extends 'layout.html' %}

{%  block content %}

    <div class="container">
        <div class="card mb-2">
            <div class="card-header">
                <i class="fa-solid fa-plus"></i>
                {{ title }}
            </div>
            <div class="card-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {%  for field in form %}
                        <div class="form-group mb-3">
                            <label class="form-label fw-bold">{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    {%  endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

ManageInterface/OSG/templates/error.html
{% extends 'layout.html' %}

{%  block content %}

    <div class="container">
        <div class="alert alert-danger" role="alert">
            {{ msg }}
        </div>

    </div>

{% endblock %}

ManageInterface/OSG/templates/index.html
<!-- mainapp/templates/index.html -->

<!DOCTYPE html>
<html lang="zh-Hant">
    <head>
        <meta charset="UTF-8">
        <title>標題</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    </head>
    <body>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    </body>
</html>

ManageInterface/OSG/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
        <a class="navbar-brand" href="#">露營區後台系統</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'OSG:admin_list' %}">管理員</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">會員管理</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">XX管理</a>
                </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-lg-0">
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'OSG:login' %}">登入</a>#}
{#                </li>#}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.session.info.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">個人資料</a></li>
                        <li><a class="dropdown-item" href="#">我的訊息</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'OSG:logout' %}">登出</a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

<!-- TODO: 以後自己寫fontawesome icon -->
<script src="https://kit.fontawesome.com/9fe3f8fab8.js" crossorigin="anonymous"></script>
</body>
</html>

ManageInterface/OSG/templates/login.html
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <style>
        .account{
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 10px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2{
            margin-top: 10px;
            text-align: center;
        }

    </style>
</head>
<body>
    <div class="account">
        <h2>會員登入</h2>
        <form method="post" novalidate>
            {%  csrf_token %}
            <div class="form-group mb-3">
                <label class="form-label fw-bold">帳號</label>
                {{ form.username }}
                <span style="color: red">{{ form.username.errors.0 }}</span>
            </div>
            <div class="form-group mb-3">
                <label class="form-label fw-bold">密碼</label>
                {{ form.password }}
                <span style="color: red">{{ form.password.errors.0 }}</span>
            </div>
            <div class="form-group mb-3">
                <label class="form-label fw-bold" for="captcha_id">圖片驗證碼</label>
                <div class="d-flex flex-row">
                    <div class="me-2">
                        {{ form.captcha }}
                        <span style="color: red">{{ form.captcha.errors.0 }}</span>
                    </div>
                    <div>
                        <img src="{% url 'OSG:captcha' %}" alt="驗證碼" id="captcha_image" style="width: 125px;">
                    </div>
                </div>
            </div>
            <button class="btn btn-primary " type="submit">登 入</button>
        </form>
    </div>
</body>
</html>